version: 2

project_name: i9c

before:
  hooks:
    - make test

builds:
  - id: i9c
    main: ./cmd/i9c/main.go
    binary: i9c
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: i9c
    directory: Formula
    homepage: "https://github.com/3v/i9c"
    description: "Infrastructure-as-Code Advisor"
    license: "MIT"
    repository:
      owner: 3v
      name: homebrew-i9c
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: i9c release bot
      email: bot@i9c.dev
    install: |
      bin.install "i9c"
    test: |
      system "#{bin}/i9c", "--help"
